### ISSUE TITLE
Benchmarks!

### ISSUE THREAD

**Issue by mhluongo** [keep-network/blake2#3]
We need benchmarks against all parameters of `F` that will be exposed in the [go-ethereum precompile](https://github.com/keep-network/EIPs/pull/2). Ideally, we want something similar to what we put together for [EIP-1108](https://github.com/ethereum/EIPs/pull/1108) so we can get gas estimates.

**Comment by pdyraga** [comment]
Benchmarks prepared and confirmed by Ethereum devs. See https://github.com/ethereum/EIPs/pull/2129/commits/7cd9f95f90a206e87be80906b4f824fee0f38efe

I am closing this issue, there is nothing more left to be done here.
