### ISSUE TITLE
Test vectors against pyblake2

### ISSUE THREAD

**Issue by mhluongo** [keep-network/blake2#5]
Generate test vectors via `pyblake2` to expand test coverage / confirm we're getting the same results across implementations.

**Comment by carterpy** [comment]
Hey @mhluongo and @pdyraga, I tried doing this yesterday and went a few circles. 
pyblake2 is in hashlib past python 3.6 and it's all Cpython. In the end though, I don't see any F-function in this standard library or in most standard blake2 libraries as far as I can tell - generally they have update and final functions like we see in [RFC 7693 appendices](https://tools.ietf.org/html/rfc7693#appendix-C.1). So at first I thought, well, let's modify pyblake2 but then I saw golang's cmd.CombinedOutput() and I figure maybe the way to roll is to make a padding function, and update and final functions to compliment the F function and emulate all the standard blake2 library functions across languages - basically just take the f function and go all the way and compare output of all the way against standard libs. Then we could add golang test functions and compare across all the blake2 libraries in all the languages if we really wanted to. 

I don't know if that's a silly approach or not. That's what I'm currently *trying* to do. If you can save me from this approach, please do lol

**Comment by pdyraga** [comment]
The current test vectors (after merging #9 today) for checksums are based on official test function published in the RFC and those from https://blake2.net/blake2b-test.txt. By testing checksums we also test F compression.

I am not sure if we need additional tests here knowing that we now compare against BLAKE2b RFC data.

**Comment by mhluongo** [comment]
I think we're good!
